//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyKaffeeService.Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kaffee", Namespace="http://schemas.datacontract.org/2004/07/MyKaffeeService.Host")]
    [System.SerializableAttribute()]
    public partial class Kaffee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GanzeBohnenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HerstellerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SorteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GanzeBohnen {
            get {
                return this.GanzeBohnenField;
            }
            set {
                if ((this.GanzeBohnenField.Equals(value) != true)) {
                    this.GanzeBohnenField = value;
                    this.RaisePropertyChanged("GanzeBohnen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hersteller {
            get {
                return this.HerstellerField;
            }
            set {
                if ((object.ReferenceEquals(this.HerstellerField, value) != true)) {
                    this.HerstellerField = value;
                    this.RaisePropertyChanged("Hersteller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sorte {
            get {
                return this.SorteField;
            }
            set {
                if ((object.ReferenceEquals(this.SorteField, value) != true)) {
                    this.SorteField = value;
                    this.RaisePropertyChanged("Sorte");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKaffeeListe", ReplyAction="http://tempuri.org/IService1/GetKaffeeListeResponse")]
        MyKaffeeService.Client.ServiceReference1.Kaffee[] GetKaffeeListe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKaffeeListe", ReplyAction="http://tempuri.org/IService1/GetKaffeeListeResponse")]
        System.Threading.Tasks.Task<MyKaffeeService.Client.ServiceReference1.Kaffee[]> GetKaffeeListeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MyKaffeeService.Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MyKaffeeService.Client.ServiceReference1.IService1>, MyKaffeeService.Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MyKaffeeService.Client.ServiceReference1.Kaffee[] GetKaffeeListe() {
            return base.Channel.GetKaffeeListe();
        }
        
        public System.Threading.Tasks.Task<MyKaffeeService.Client.ServiceReference1.Kaffee[]> GetKaffeeListeAsync() {
            return base.Channel.GetKaffeeListeAsync();
        }
    }
}
